npm/newww

facets/registry/show-package.js
test/fixtures/fake.json
test/registry/package.js

Issue was that when a user was logged in, the packages that they have
already starred did not appear as such. Now it all works again yay!

Fixes broken star issue

---

assets/styles/layout.styl

This change makes it so that links inside of .box in the right sidebar on package's page turn "npmred" on `.box a:hover` and not on `.box:hover` which causes all links in the parent .box to be turned "npmred" which, imo is bad UX.

Fixes :hover on links in the right sidebar.

---

assets/misc/opensearch.xml
routes.js
templates/layouts/default.hbs

Before:
After:
I stuck it in `assets/misc` since it seemed like the right place for it

re-add opensearch.xml

---

facets/registry/show-package.js
services/registry/browseUtils.js
services/registry/methods/getBrowseData.js
test/fixtures/mock-server-methods.js

When hapi caches a method call, i.e. `getBrowseData('depended', 'underscore', 0, 1000, cb)`, it stores the generated object in redis with a key that looks something like `getBrowseData:depended:underscore:0:1000`. However, we recently made a change that allows the first argument to be an object, i.e. `getBrowseData({type: 'depended', noPackageData: true}, 'underscore', 0, 1000, cb)`. Since Hapi doesn't know what to do with objects as parameters when storing items in the cache, it
simply never caches.

Fixes broken caching due to getBrowseData arg types

---

assets/styles/layout.styl

The only other elements that don't have border-radii on the packages page are the code blocks; I've added a border-radius as a further way of differentiating the ad, in addition to the current border.

Added border-radius to the ad class

---

assets/styles/readme.styl

The tables in the READMEs looked a bit off without any styling. I tried to add a style similar to the code block styles, with a #f5f5f5 background and some padding.
I don't know what kind of style you are going for here. Do you think the background looks OK, or should it simply have borders or no background at all?
---
---

Adds style for tables in readme section

---

assets/styles/readme.styl
dev/replicate.js
facets/registry/show-package.js

Don't attempt to validate package names before fetching, because the rules have changed along the way. Only validate if a package is not found, so we can vary the message shown to the viewer. (Now-invalid names do not get any encouragement to publish with that name.)
Added `JSONStream` to the list of replicated packages for verification.

Fixed issue #499: handle mixed-case package names

---

config.js

This is happening on https://www.npmjs.com/npm-weekly:
But this PR will fix it. :)

allow remote mailchimp script

---

README.md

Now that the `npm test` is only doing one thing, we can run `npm t -- some/dir`. Yay!

updating testing section of readme

---

assets/scripts/private-npm-beta.js

I think this is the issue mentioned in #296. What I did was override the submit button class to remove the `hs-button` class, which was making the button blue.

Fix submit button style on the private-npm page

---

.env.example
facets/user/show-signup.js
locales/en_US/user.js
package.json
server.js
services/user/methods/signupUser.js
templates/user/signup-form.hbs
test/fixtures/fake-couch.js
test/services/user.js

Will fix #555 when it's done.
I figured I'd take a shot :) This is a first pass at adding mailchimp to the sign up flow. The `xxx` in there is a placeholder for the auth token. Where do we put that kind of config?
Also, it doesn't do anything on success or error. I don't think we want to display anything to the user, but should we log errors?

add npm weekly subscription opt-in to sign up

---

gulpfile.js

We're now using jshint, thanks to @ckross01 and @rockbot!
`gulp lint` works like a charm, but it's a little much to have it running on `gulp build` right now, because we have lots of files that don't meet our jshint requirements.
This PR disables linting on build for now until we are in a more stable state, and can do a sweeping "add semicolons to 100+ files" PR.

jshint setup

---

assets/styles/markdown.styl
assets/styles/typography.styl

Every once in while there's a style regression with h1s and h2. The package page, the local pages, and the githubby static pages all kind of battle each other, dom-hierarchy-wise.
Package page
Local page
Githubby

the monthly h2 wrestling match

---

facets/registry/show-package.js
test/registry/package.js

The major benefit of this change is that now when a package is unpublished, google search will hit the page but refrain from putting it in their search results, as per http://searchenginewatch.com/sew/how-to/2340728/matt-cutts-on-how-google-handles-404-410-status-codes#

Changes status code for unpublished package pages from 200 to 410

---

package.json

I tried to run the site on iojs 1.0.3 and got some gulp errors. This version bump fixes it.

update gulp for iojs compatibility

---

assets/misc/robots.txt

Per http://stackoverflow.com/questions/671491/robots-txt-allow-only-major-se this may resolve a recent drop in search traffic we've noticed.

Let major search engines hit /browse/ pages

---

routes.js
templates/enterprise/index.hbs
templates/layouts/default.hbs
test/company/home.js

We say "npm Enterprise is private npm" but then "private npm" links to the "npm Private Modules" page, and it's all confusing.
This clarifies a bit while hopefully not destroying our SEO goodness.

clearer use of 'private npm' copy

---

assets/styles/layout.styl

Currently, the hover styles look like this:
Post change, they should look like this:
*caveat I didn't build locally*

Fixing the hover styles for last-publisher links to not underline whitespace

---

lib/csp.js
routes/public.js
test/csp.js
test/routes.js

From @jlamendo:
> the hubspot CSP urls are not restrictive enough, and could cause a bypass if a less restrictive injection point were to be found. I know it results in adding to an already lengthy CSP header, but you should whitelist specific pages on hubspot, or at least only allow pages located within your client ID folder.
It would be nice to factor out the hubspot config from `config.js` into its own module like `lib/hubspot.js` and stop passing config through the handlers, but it's tangled and I don't want to go down a rabbit hole this morning.

A more restrictive CSP for Hubspot

---

assets/misc/google17836d108133913c.html
routes/public.js
test/handlers/static.js

Instead of manually adding a route for every file in `/static/misc`, this iterates over the contents of the directory and creates a route to serve each from `/`. This means less code, and the next time you add a file to `/assets/misc`, it will be served from `/` without the need for a new route.
PS This also fixes a path bug I introduced last Friday. :)

DRY static routes

---

assets/styles/_header.styl

So it turns out that `darken (greigh5, 10%)` doesn't actually do anything. I tried up to 200% and it had no change, so I just switched to `greigh4`.
I'm also compiling the changes now so I can actually confirm the results :smile:

Changing #npm-search hover from darken(greigh5) to greigh4

---

templates/registry/package-page.hbs

Fixes #625 
The applicationCategory and offers values are a little weird. I added them because you're required to have 2 of 4 optional fields, and those two were the closest to making sense for our use case (the other two are aggregateRating and operatingSystem).
This could potentially go in `package-page.hbs`, but I wasn't sure whether canonicalURL was/should be exposed as a variable there.

add schema.org metadata to package pages

---

templates/registry/package-page.hbs

Fixes #645 and removes excess template logic.

use the same delimiting style for dependencies and dependents

---

.env.example
handlers/homepage.js
handlers/package.js
lib/cache.js
lib/environment.js
models/download.js
package.json
server.js
test/cache.js
test/models/download.js

@ceej I started adding more tests, but got stuck with sinon and scope stuff and need your input:
- Some of our tests were (wrongly) passing before because we had `to.be.true` assertions instead of `to.be.true()`
- The `get() calls _fingerprint()` test is only passing now because I changed the code to use `exports._fingerprint()`. This is obviously not the right way to do it. Please advise.
- I suspect this is the same reason the logger tests are failing too.
- In the later tests I'm calling `cache.redis.set.restore();`, but subsequent tests are whining: `Attempted to wrap set which is already wrapped`.. is this a race condition or something?

redis cache thing

---

config.js

I deleted my local `config.admin.js` because I want the default config to Just Work. This change gets us a little closer to that.

Use default redis port

---

assets/styles/forms.styl
assets/styles/typography.styl
config.js
facets/user/show-profile-edit.js
facets/user/show-resend-email-confirmation.js
facets/user/show-signup.js
locales/en_US/user.js
models/download.js
models/package.js
presenters/user.js
templates/partials/email-verify-nag.hbs
templates/user/billing.hbs
templates/user/email-confirmed.hbs
templates/user/email-edit.hbs
templates/user/password.hbs
templates/user/profile-edit.hbs
templates/user/profile.hbs
test/adapters/bonbon.js
test/fixtures/users.js
test/handlers/user/edit-profile.js
test/handlers/user/login.js
test/handlers/user/resend-email-confirmation.js
test/handlers/user/signup.js
test/presenters/user.js

Fixes https://github.com/npm/newww/issues/686 and https://github.com/npm/newww/issues/755

Signup and Email Confirmation Flows

---

services/email/methods/send.js

This is a fix for https://github.com/npm/newww/issues/783

simplify `from` addresses to avoid escaping issues in email templates

---

handlers/star.js

The correct order of operations here is `Promise.then(normal-flow).catch(error);`
If you catch an error, return from that function, then pass the result along to a then(), whatever's in the then will be executed. If you want it not to be executed, you need to cancel the promise in the error handler. However, the pattern `then().then().catch()` is the expected use of promise chains, and that's what we're now doing here.
Caught this because a misconfigured service was causing all star operations to error, which then caused a double-reply error in www.

Promise.catch(err).then() considered incorrect.

---

assets/styles/forms.styl
assets/styles/layout.styl
assets/styles/typography.styl
assets/styles/variables.styl
templates/package/show.hbs

This fixes that whitespace above the sidebar on package pages, and lowers the "switch to mobile" threshold from 900px to 767px.

use percentages for a more adaptive mobile/desktop package page

---

models/user.js

Don't add bearer token to request if user is not logged in.
This was crashing the profile page for logged-out users.

no null bearer

---

handlers/homepage.js
lib/cache.js
models/package.js
test/cache.js
test/models/package.js

The package "model" now uses the cache for all package data gets. It drops any cached data for a specific package on update. There is now a convenience function for generating the predictable package Request options, so it is guaranteed to look the same every time.
Added promisified versions of `cache.get()` and `cache.drop()` for convenience, called `cache.getP()` and `cache.dropP()`. Added unit tests for the promisified wrappers.
Adjusted two package "model" tests to look for the regularized error messages that the cache generates on 404s.
While I was looking at it, parallelized the queries that build the home page, which should result in a modest speed improvement.
All tests pass. This of course means success is assured.
cc @rockbot, @bcoe

Registry relational queries are now cached.

---

facets/registry/show-search.js

We were leaking client connections like a sieve. The config never changes; there's no need to create a fresh object every time.

Don't make a fresh ES client on every request.

---

handlers/customer.js
lib/cache.js
lib/external-request.js
lib/utils.js
models/collaborator.js
models/customer.js
models/package.js
models/user.js
package.json
test/adapters/bonbon.js
test/cache.js
test/external-request.js
test/handlers/access.js
test/handlers/customer.js
test/handlers/package.js
test/handlers/user/login.js
test/handlers/user/signup.js
test/models/user.js

addresses https://github.com/npm/newww/issues/860
note that we're now logging the `body` coming from the Request calls in errors - this is because the error messages that come from the LICENSE_API are actually being sent in the body, and not in the `err` param.

adds logging for external apis, plus test fixes

---

lib/csp.js
package.json
test/csp.js

This is a fix for https://github.com/npm/newww/issues/885
Not sure why we weren't seeing this until now, but the stripe code currently expects to be able to use an iframe. 
When adding stripe to the `frameSrc` whitelist, I noticed that [frame-src is deprecated](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#child-src), so I updated the CSP to use `child-src` instead.
This is up on staging now for testing.

Update Stripe config in CSP

---

assets/scripts/package-access.js
handlers/access.js
templates/package/access.hbs
test/handlers/access.js

It is currently possible for an unpaid user to toggle their public package to private, effectively locking themselves out of the package until they become a paying customer. This PR addresses that problem.
When all of the following criteria are met...
- package is scoped
- package is public
- user is logged in
- user has write permissions to package
- user is not a paying customer
...then the public/private toggle is hidden and replaced with a notice:
If the user is a paying customer, they see the private/public toggler:

Disallow private toggle for unpaid users

---

templates/user/billing.hbs
templates/user/email-confirmed.hbs
templates/user/profile.hbs
test/handlers/customer.js
test/handlers/user/confirm-email.js
test/handlers/user/profile.js

It was on the profile page. Now it's on the billing page. So the following actions will presumably satisfy the conversion requirements:
1. sign up (as an npm user)
1. confirm email
1. go to billing page

move twitter signup tracking code

---

package.json

2.1.0 breaks functionality. See hapijs/hapi-auth-cookie#67

pin hapi-auth-cookie to 2.0.0

---

README.md

The CSP configuration doesn't seem to be in config.js anymore.

update csp location in README

---

services/email/methods/send.js

This is to avoid confusing Zendesk, which doesn't like that the from: and to: fields are the same right now.

Website now sends email from website@npmjs.com

---

facets/user/show-forgot.js
facets/user/show-login.js
facets/user/show-password.js
test/fixtures/users.js
test/handlers/user/password.js

The key was to put the `mustChangePass` directive into the resource section, as it wasn't getting saved to user-acl.
Due to some user-acl limitations, we have to use a string instead of a usual boolean - fortunately we can nullify it, so `if user.resource.mustChangePass` still works just fine :-)

encourages password change after password reset, fixes #798

---

handlers/ops.js

A fix for https://github.com/npm/newww/issues/863
When introducing a CSP violation in my dev environment, it appears that Firefox is the only browser that acutually POST to the report endpoint. Chrome and Safari both dump error messages to the browser console, but they don't report. Hmm.

don’t parse request.payload for CSP report, as it is already JSON

---

.env.example
facets/company/show-send-contact.js
package.json
test/company/contact-support.js

Review please: @rockbot 
In the future, we probably also want to send general inquiries and security tickets into Zendesk, but with different magic ticket flags so that we can route them appropriately.

contact: Send support requests directly to Zendesk

---

assets/styles/README.md

Updated the link for the `nib` package to point to the current documentation.
Also removed some small grammatical errors, and for fun threw in some unnecessary stylistic changes.

Update nib link + grammar changes + trivial stylistic choices

---

models/package.js
test/handlers/star.js

Not sure if this is the best solution, but essentially we were passing `@scope/package`, which was breaking the url we use to send the star to the user-acl. Instead, we should be sending `@scope%2fpackage` so that it doesn't seem like we're sending to a different url.
Using `encodeURIComponent(package)` would result in `%40scope%2Ffpackage`... would that work better?

allows starring of scoped packages (fixes #879)

---

facets/user/show-confirm-email.js
facets/user/show-email-edit.js
facets/user/show-forgot.js
locales/en_US/index.js
templates/errors/token-expired.hbs
test/handlers/user/confirm-email.js
test/handlers/user/email-edit.js

Two tests are missing (in `test/handlers/user/forgot-password.js`)
```
Using a token
- 14) renders an error if the token does not exist (0 ms)
- 15) changes the password with a proper token (0 ms)
```
Both of these were commented out some time ago; bringing them back requires some pretty significant rewrites across multiple modules. In essence, we're using three different cache mechanisms and we should really consolidate it down to one. An issue has been created here: https://github.com/npm/newww/issues/1000.
The other tests totally pass, though, and hand-testing seems to work just fine.

adds messaging to inform user that token has expired (fixes #167)

---

services/email/methods/send.js
test/services/email.js

should be merged in conjunction with https://github.com/npm/email-templates/pull/7

separates support email from 'from' email (fixes #976)

---

lib/cache.js
test/cache.js

Those info lines are now debug lines, so we don't spew a lot of logging on every cache operation. Also, we no longer uselessly log `[object Object]` as the cache key in those lines.
Updated the test that looked for the info log.

Silence the cache logging in normal operations.

---

presenters/user.js
test/fixtures/users.js
test/presenters/user.js

non-ending if-tree resulted in `undefined` homepage when user tried to delete homepage from profile, which made user-acl angry and resulted in a non-deletion of the homepage :-/
but now it's all fixed, so yay! :-D

fixes homepage editing bug

---

templates/layouts/default.hbs
templates/user/billing.hbs

HTML5 specifies default values for the `type` attribute for [`<script>`](http://www.w3.org/TR/html5/scripting-1.html#attr-script-type), [`<style>`](http://www.w3.org/TR/html5/document-metadata.html#attr-style-type), and [`<link>`](http://www.w3.org/TR/html5/document-metadata.html#concept-link-type-sniffing) elements so, unless a different value is needed, the default can be omitted.

Remove optional `type` attributes from templates

---

facets/registry/show-search.js

Brutal simplification of the ElasticSearch query produces results that are a lot more like what you'd expect for searches like "hash ring", "leveldb cluster", and "regexp escape". ES now does all the result relevance work.
While I was there, fixed jshint complaints.

Fixed bug #894: search is using OR instead of AND

---

AUTHORS
AUTHORS.md

There are [many tools](https://www.npmjs.com/search?q=contributors) on npm for assembling a contributor list from git/hub. I tried about five of them, but none of them fit my requirements: Some didn't work at all, others didn't have a CLI, some produced tons of crazy HTML output, some put the contributors list in package.json...
So I spent a few minutes working on rolling my own: a little script that hits the github API, stuff the contents into a handlebars template, etc. But today is not a yak-shaving day. It's a day to get things done and move on.
I present a minimalist fix for https://github.com/npm/newww/issues/901

let github tell the contribution story

---

assets/styles/_header.styl

Hi guys,
We're glad to hear the autocomplete is working out great!  We're really excited to be providing the service.
We showed the branding edit you guys made to some people, and they didn’t notice our name, so we'd like to suggest one small tweak to make it slightly more prominent.  If we match the background color to the gray in your heading, we get something like this:
Is that cool?

tweak Constructor.io background color

---

locales/en_US/company.js

This caused some confusion and we shouldn't be using dot org email addresses anywhere.

Update whoshiring email address to .com

---

adapters/bonbon.js

If a package had 'static' in the name, the url wasn't being
authenticated against. We'd like to not go through the process of
AUTHing requests for static files, but of course don't want to log
people out because they look at a package that has 'static' as part of
the title.
Fixes #1032

Overzealous regex was logging people out

---

routes/public.js
templates/company/private-modules.hbs

Fix #1043 
Add new route for `/private-modules` - have it async grab the benefits (plus sign-up button) of private-modules + the private-modules copy separately and then only display the benefits + sign-up button if the user hasn't paid.

Fixing #1043 by separating static content

---

adapters/bonbon.js
facets/company/show-policy.js
facets/company/show-static.js
facets/company/show-whoshiring-payments.js
facets/company/show-whoshiring.js
facets/enterprise/buy-license.js
facets/enterprise/find-license.js
facets/enterprise/show-index.js
facets/registry/show-search.js
facets/user/show-confirm-email.js
handlers/star.js
server.js
services/downloads/methods/getAllDownloads.js
services/user/methods/sessions.js

Changed all names to graphite style dot-delimited strings. In particular, all the latency metrics are now things like `latency.page` and `latency.redis`.
Added a `value` field to all metrics.
Removed metrics that are redundant since we're already emitting a latency metric with the page name in it.
Fixed all jshint complaints while I was there.
The web site now emits the following metrics:
| name | value | additional fields |
| --- | --- | --- |
| 'server.start' | 1 | env |
| 'latency.page' | latency in ms | page |
| 'latency.stripe' | latency in ms |  |
| 'latency.licenseCreation' | latency in ms |  |
| 'latency.elasticsearch' | latency in ms |  |
| 'latency.downloads' | latency in ms | package |
| 'latency.redis' | latency in ms | action='setSession' |
| 'latency.redis' | latency in ms | …

Metrics tweaks.

---

lib/external-request.js

The hostname is sent in the `source` field, with any trailing `.internal.npmjs.com` stripped off.

Emit latency metrics for all external requests.

---

facets/registry/show-search.js
package.json

fixes #1029 and #1066 
when we updated search we forgot to push the exact-name matches to the top. this is now fixed :-)

packages with the searched name are definitely at the top now

---

templates/layouts/default.hbs

Also, render page before requesting for js
Easy, yet big win!
I would do this with css as well, but as of right now, it's a difference of 500B and we'd have to add another tool to the toolchain, so we'll wait on that.

Make sure to serve minified js on servers it should be minified on.

---

adapters/bonbon.js

Hang the session id field onto the `loggedInUser` object so the value is available later on when attempting to act on the session in redis.
No tests yet, because the login/logout code has no existing tests to build on, and shaving that yak is a task for another day.

Fixed issue #43: www sessions are not correctly expired in redis on logout

---

README.md

There isn't any "static" folder in this repo (cause it's being ignored in .gitignore file), so a link to this folder is actually a broken link.

Improve Stylus' build instructions

---

routes/public.js

similar to PR of 2015-08-04, but new URL of destination reflecting pointing a CNAME (info.npmjs.com) to HubSpot pages for improved user peace-of-mind

adds alias to point /orgs to HubSpot form page

---

gulpfile.js
templates/layouts/default.hbs

when we update vendor scripts, they get concatenated into vendor.min.js. It turns out we're caching vendor.min.js as well, so this PR lets us avoid the manually-nuke-the-cache issue.

adds vendor.min.js to versioned, cache-busting workflow

---

presenters/package.js
test/presenters/package.js

in general, urls that execute javascript (for example) _should_ be caught by the CSP, but in case they aren't, this PR should add another level of protection.

removes urls that aren't actually urls

---

lib/cache.js
package.json
test/models/user.js

It does this by clearing the cached item before the tests that use it.
Also, adds debuglog calls that can be enabled with `NODE_DEBUG=newww:cache`
to show what's going on in the cache layer at runtime for diagnosing these
sorts of issues.

Fixes test/models/user.js to be runnable twice in rapid succession

---

templates/layouts/default.hbs

1. We added the recruitment policy
2. Adding an extra link messes up the symmetry of the footer
3. We'll probably want to add extra policies
4. It's okay if the trademark policy is 1 click further away
Conclusion: this PR.

Link to policies page so we can add N additional policies

---

package.json
presenters/package.js
test/presenters/package.js

This brings in [`normalize-package-data`](https://github.com/npm/normalize-package-data#readme) and then picks specifically acceptable things out of what it presents.

normalize package data, and use URLs with known schemes for homepage and repositories

---

agents/org.js
assets/styles/org.styl
templates/org/info.hbs

adds list of org packages on org overview tab (fixes #1155)

---

templates/enterprise/clickThroughAgreement.hbs

marketing + sales experiment to observe whether npmE sales meets less resistance if copy does not pre-emptively expect users to take issue with licensing text

copy variation on npmE licensing clickthru

---

assets/styles/_header.styl

We are changing how the constructor-autocomplete widget works, so this
will be necessary to get the ad to line up properly after.
Without the PR, with our change to the widget:
With the PR, with our change to the widget:
We made an abortive PR two hours ago, but this one is the actual PR

Adds a negative margin to the constructor.io ad (round 2)

---

assets/scripts/billing.js

the issue was simple: since we don't show the credit card form when we already have billing information, we were sending an empty object to stripe, which caused a 400. this PR fixes it. :-)

fixes bug where already-paid user was unable to create an org

---

routes/public.js
test/handlers/org.js

even though the `/orgs` redirect works, it doesn't carry the query parameters along, so we have to be explicit about it.
also: added some tests to ensure no regressions later on.

allows /orgs?join-beta to work as well (fixes #1250)

---

facets/user/show-profile.js
templates/user/profile.hbs
test/adapters/bonbon.js
test/fixtures/orgs.js
test/handlers/user/edit-profile.js
test/handlers/user/profile.js

Note: this only works if you are logged in, are looking at your profile page, and have created organizations. If you have no orgs, are not logged in, or are looking at someone else's profile page, you will *not* see any org lists.

adds list of user's orgs to profile page if they are logged in

---

templates/layouts/default.hbs

This should be at the top of the document per HTML5 spec. Well, not exactly at the top, but in [first 1024 bytes](http://www.w3.org/TR/html5/document-metadata.html#charset) (Mozzilla somewhy [says that first 512 bytes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset)).
And you have user-controlled `<title>` of indefinite length above it now (tested ~3KiB). The same for `twitter:description` (didn't test length).

Move <meta> charset tag to the top, above <title>

---

models/customer.js
test/handlers/org.js
test/models/customer.js

Accepting a sponsorship specifically returns a 409 in the case that a
user is already sponsored (and no longer returns a 500).
Fixes #1294

Change status code being listened for to 409

---

adapters/plugins.js
package.json
server.js
services/corporate/index.js
services/downloads/index.js
test/mocks/server.js

a few API changes, as per the [9.0.0 Release Notes](https://github.com/hapijs/hapi/issues/2682). This PR will set us up for [hapi 10.x](https://github.com/hapijs/hapi/issues/2764), which has zero API changes, but will allow us to transition to Node 4.
if I've learned anything from this PR, it's that I look forward to the day when we no longer need `mocks/server.js`, which is a huge pain and leaves `server.js` completely untested.

updates the codebase to hapi 9.x

---

templates/package/show.hbs

Hi npm!
No license (or a license lacking a url, though I haven't come across any of those yet) currently looks like:
For consistency with the other fields, it could look like:
Not a big deal, but happened to notice it as I was poking around. :)

License name is strong.

---

presenters/package.js

We seem to default to the latest release in the UI.
An example URL that is affected by this is `/package/formula` which
claims an error with this check and displays fine with a correct version
as the latest release without it.
Fixes #1342.

Remove check for `version` property in Package presenter

---

package.json

as far as I can tell, we don't use the npm2es dependency in newww (this service is deployed separately, and has its own operational concerns). The git dependency causes issues for the Alpine server I'm building newww on (CC: @aredridel).

we don't use the npm2es depdendency in the www codebase

---

lib/external-request.js

Extends the error with context (the URL requested) and keeps intact any
custom properties on the original error.

Improve error reporting

---

assets/styles/layout.styl
templates/homepage.hbs

This patch moves the "getting started" bits from the bottom to just below the "things people install a lot" bit, and reduces the logo bunch so that they take up a lot less space.
I'm a bit out of practice with doing frontend stuff, and especially there's probably some stylus stuff that should be done differently.  But it seems like this sorta works?  I guess?
Review welcome, and deployment not at all urgent.  This is just something that's been bugging me for a while :)

homepage: move 'getting started' above the fold

---

templates/partials/form_security.hbs

So, this is a potential fix for the problem whereby LastPass is populating the honeypot field.
It requires LastPass to be appropriately configured (https://forums.lastpass.com/viewtopic.php?f=6&t=78817), but at least it shows goodwill on your part

Potential fix for the LastPass problem

---

templates/enterprise/find-license.hbs
templates/user/login.hbs
templates/user/signup-form.hbs

Microsoft Edge (their latest browser) doesn't like empty `action` attributes on forms, which was why users were unable to login or signup on our website.
This PR fixes that (and other missing action attributes) :-)

fills in missing form actions (fixes #1358)

---

adapters/bonbon.js
assets/scripts/vendor/constructor-io.js
assets/styles/_footer.styl
assets/styles/_header.styl
templates/layouts/default.hbs

This reworks the top bar for non-npmo web installations (hello public site!) so look at these screen shots.
Before:
After, not co-branded:
After, co-branded:

Co-brand a bit with On-site users to make npmo stand out

---

adapters/bonbon.js
lib/feature-flags.js
test/adapters/bonbon.js
test/feature-flags.js
test/fixtures/users.js

there's some repeated code in bonbon.js - L19-26 and L48-56 - but I'm not sure what the best way to DRY that up is... thoughts, @jefflembeck, @aredridel ?
In particular, do we keep some of that logic in adapters/bonbon.js or move it into lib/feature-flags.js?

allows feature flags to be set via user's resource

---

package.json

addresses #1403
but it looks like engines will only throw a warning upon install.

added engine

---

lib/startup.js

Looks like this should be `includeSubDomains` (http://hapijs.com/api)

fix includeSubdomains typo

---

agents/org.js
handlers/customer.js
handlers/org.js
routes/authenticated.js
templates/org/billing.hbs
templates/org/create.hbs
test/agents/org.js
test/fixtures/orgs.js
test/handlers/customer.js
test/handlers/org.js

fullname is an optional attribute for an organization that is currently
stored in the user-acl `resource` hstore (as `human_name`) but will eventually become a
column on that model.
Since it is stored as `human_name` on the user-acl, we finesse it a
little along the way.
This updates tests, fixtures, handlers, and the agent

Add support for an Org's "full name"

---

agents/customer.js
agents/org.js
handlers/org.js
test/handlers/org.js

We've got a 500 on production and it needs handling.
This change involved some serious promisifying of our handler, so I could better track the errors - 4xx errors are now displayed as notices while 5xx errors are sent to an internal page.
Test added for 500.

Handle 500 delete

---

adapters/metrics.js

If process.env.METRICS_URL is set, we make a real emitter. Otherwise, we make a stub that does nothing when called. This allows us to change the configuration in production by changing settings in etcd, without having to change code. It also allows us to not try to connect to a non-existent metrics collector in dev or test.
To get metrics flowing in production again, we'll need to accompany this change with
`renv config set -e production -a newww service.env.METRICS_URL=whatever`

Only make a metrics emitter if there is config asking for one.

---

templates/layouts/default.hbs

This PR follows on from npm/policies#16 and npm/npm#10326 with a small
change to the "Legal Stuff" footer. Long story short, it makes the top
link to "Terms of Use" and <https://wwww.npmjs.com/policies/terms>,
which corresponds to a new `terms.md` file in npm/policies. That file in
turn links to terms of use for npm Open Source, npm Personal, and the
CLI LICENSE.
Longer term, npm can add terms for specific products to npm/policies and
link to them from /terms without creating a massive list of terms at the
bottom of each page on newww.

Link to terms of use first in "Legal Stuff" footer

---

handlers/team.js
templates/team/show.hbs
test/handlers/team.js

Now it looks like this: <img width="1133" alt="screen shot 2015-11-19 at 11 11 34 am" src="https://cloud.githubusercontent.com/assets/954269/11281195/5db6b1a2-8eae-11e5-8f5c-59d60fda32c8.png">
(Note if we're missing data, we're just showing a blank entry.. that may very well be that my one package is broken though - everything else seems to be just fine.)

adds missing detail to team package page (fixes #1520)

---

agents/team.js

Some team names may have slashes in them — usually ones from package teams ported over as part of a "user to org" operation.

encode teamname in user-acl team requests

---

templates/org/members.hbs
templates/team/show.hbs

also removes the `date added` column (which was filled with just "date" because we don't actually have that data).

adds roles of users to org member page (fixes #1556)

---

handlers/org.js
templates/org/members.hbs

basically makes this happen: 
it's not much, and until a fix is made in the user-acl, a super admin can still delete themselves via the cli.
thoughts? cc @seldo, @chrisdickinson, @ncawthon

disables ability to remove super admin from an org (fixes #1564)

---

handlers/org.js
test/handlers/org.js

users who are unpaid super-admins (for whatever reason) are unable to access the org page. this PR fixes that.
That said, we've got the following issues:
1) this PR doesn't necessarily prevent unpaid super-admins from at least attempting to add/remove users. What do we do about that?
2) I'm not sure that this is the best way to use promises for what we want to achieve. In particular, the tests will pass, but the following will pop up as well: 
```shell
Unhandled rejection Error: Customer not found
at Error (<anonymous>:null:null)
at /Users/rockbot/npm-inc/newww/agents/customer.js:38:15
at Request._callback (/Users/rockbot/npm-inc/newww/lib/external-request.js:38:12)
at Request.self.callback (/Users/rockbot/npm-inc/newww/node_modules/request/request.js:198:22)
at Request.emit …
```

allows unpaid super-admin to still access org

---

agents/org.js
test/agents/org.js
test/handlers/customer.js
test/handlers/org.js
test/handlers/team.js

This fix is not comprehensive, as we'll hit it again when an org has more than 100 users, but that requires a bit of refactoring.
This fix fixes the issue where if there are more than 25 members to an org, we don't recognize that.

Add view team members

---

agents/org.js
test/agents/org.js
test/handlers/customer.js
test/handlers/org.js
test/handlers/team.js

Much like the fix for #1596, this is temporary.
The method for grabbing packages is now grabbing the first 100, instead of the first 25 packages. This will hold us off until we refactor to better cover this.

Pagination for Org packages

---

package.json

By bumping marky-markdown, we fix a 500 error that was being caused by image urls in this format:
`![Methods](#methods)`
I think what the user actually intended was `[Methods](#methods)`, but better that we handle this edge-case without exploding.
we should test thoroughly because `marky-markdown` `5.4.0` -> `5.5.1` updates quite a few dependencies:
CC: @ceejbot @ashleygwilliams

bump marky-markdown dependency

---

handlers/org.js
test/handlers/org.js

A 404 on an org is currently causing a redirect loop.
This fixes that.
Fixes #1611

Make sure 404 turns out a not found page

---

test/agents/team.js

Change expected error message from `Team or Org or not found` to `Team or Org not found` (one too many `or`s in the first one).
Fixes the `addPackages() returns an error if something goes wrong` test.

Fix expected error message in addPackages() test

---

.gitignore
README.md
package.json
server.js

Undo #1417 and fix #1649. Removes the `newrelic` module and any mention of its requirements/resources.

Remove newrelic module

---

handlers/access.js
templates/layouts/default.hbs

Also block the access pages from search engine indexing
If you Google "parse messy schedule" the first result is the Github repo and the second is the "access" page. The package page itself doesn't show up.
Since `access` is an administrative page without a lot of useful information for non-maintainers it shouldn't be indexed.

Set up mechanism to prevent page indexing.

---

templates/layouts/default.hbs

Makes it easier to distinguish between npm On-Site and the public registry site in browser tabs.
Plus it makes npmo that much more customized for our awesome customers!
Public registry tab:
New and improved On-Site tab:

Give npmo its own default page title based on customer name

---

templates/registry/search.hbs

Of the four templates that include a `.hiring-container` (for displaying a who's hiring list), only the package search result view (`templates/registry/search.hbs`) neglects the check for `features.npmo`.
This fixes that.

Do not include hiring-container in search view for npmo mode

---

agents/customer.js
handlers/org.js
test/agents/customer.js
test/fixtures/orgs.js
test/handlers/org.js

We will frequently be needing to reference parts of the license instead of just the `license_id`. A highlight to this is that we can do this all in one call now, instead of having to make the call and then loop through.
Also:
Cleanup some linting errors on org handler
Update tests

Move to getLicenseForOrg from getLicenseIdForOrg

---

agents/customer.js
handlers/org.js

We no longer need this safeguard, and the 403 isn't the right error to
send back

A 409 is returned from the server in production

---

templates/partials/org-nav.hbs

there's a bug in the u2o newww-tests test, in which we need to click on the `members` tab to see the members in the org... but in order to click on the tab, we need some sort of defining characteristic; a class will do just the trick.

adds classes to org nav to appease the newww-tests deity

---

adapters/bonbon.js
test/adapters/bonbon.js

also reordered the lifecycle extensions to be [in order](http://hapijs.com/api#request-lifecycle).

ensures charset=utf-8 on response headers (fixes #1301)

---

agents/org.js
test/agents/org.js
test/handlers/customer.js
test/handlers/org.js
test/handlers/team.js

This is a temporary fix, similar to how we handle users and packages.
It includes expanding the amount of teams that come back from the user-acl
It also updates handler tests to reflect query strings.

Make sure up to 100 teams can show on an org page

---

facets/enterprise/show-verification.js
facets/registry/show-search.js
handlers/access.js
handlers/homepage.js
handlers/package.js
lib/error-handler.js
lib/utils.js
services/npme/methods/verifyTrial.js
templates/errors/internal.hbs
templates/helpers/encode.js
test/adapters/bonbon.js
test/enterprise/verification.js
test/handlers/access.js
test/handlers/homepage.js
test/handlers/package.js
test/mocks/server.js
test/registry/search.js

Meant to address #1501.
Things changed:
- Error handling in `handlers/homepage.js` adds a `npmoFullStack` property to the view context
- The `templates/errors/internal.hbs` view renders slightly differently when the `npmoFullStack` context property is defined:
- Uses `container` instead of `container narrow` class on outer div
- Displays a slightly different message that displays the support@npmjs.com email and no longer mentions twitter or IRC
- Displays full stack trace of error instead of just a correlation ID
Things still missing:
Things I don't like about the current implementation (and would like feedback on):
1. In order to provide a "full" stack trace to the user, I copied the private `stackToString` method from `bole` and stuck it in `lib/utils.js`. I figured it was either this …

Support for npmo-specific error page

---

package.json

We are deeply concerned that we are already in 2016, but **npm expansions** in the live website seem to be as old as from **August 14, 2015** ([version 2.2.1](https://github.com/npm/npm-expansions/tree/v2.2.1))!!!
This is absurdly unnaceptable. This utmost treasure of highest wisdom cannot be ignored and just wasted like this. We need urgent action!
The community is worried about current state of affairs: https://github.com/npm/npm-expansions/issues/881
**N**ow **P**lease **M**erge this Pull Request immediately so we can finally share these highly valuable contributions with the world.
In my humble opinion, not even an update to 2.2.3 is enough... this version is already 18 days old and we already have [26 new brilliant contributions](https://github.com/npm/npm-expansions/pulls) since …

Update npm-expansions to 2.2.3

---

package.json

- we were parsing `:)` into emoji, though this is not the desired behavior.
disabled shortcut emoji parsing in the markdown-it-emoji plugin. 
([issue/95], [pull/97]) - reported by [cloakedninjas], solved by [revin]
- `markdown-it@5.1.0` would break the build, so `package.json` was updated
to hold at minor version, `~5.0.2` ([pull/90][pull/93]) - by [ashleygwilliams]
[cloakedninjas]: https://github.com/cloakedninjas
[pull/97]: https://github.com/npm/marky-markdown/pull/97
[issue/95]: https://github.com/npm/marky-markdown/issues/95
[ashleygwilliams]: https://github.com/ashleygwilliams
[pull/90]: https://github.com/npm/marky-markdown/pull/90
[pull/93]: https://github.com/npm/marky-markdown/pull/93
[revin]: https://github.com/revin

bump marky to 6.0.2 for bug fixes

---

assets/scripts/billing-cancel.js

Revert "Unambiguously stop hiding the update payment info screen if it applies"
This partially reverts commit 610e8ee374c7c1f328fb43467d23881cf8dbdd15.

Revert part of commit that hides cancel payment

---

adapters/bonbon.js
test/adapters/bonbon.js
test/fixtures/users.js

Users with names that are properties (lower-case only) on Object would
pass this test and be able to see the json we pass to the context. Using
`hasOwnProperty` instead of `in` fixes this

This fixes a possible viewing of the context' json

---

test/company/contact-support.js
test/enterprise/buy-license.js
test/enterprise/find-license.js
test/enterprise/trial-signup.js
test/enterprise/verification.js
test/fixtures/enterprise.js
test/handlers/user/email-edit.js
test/handlers/user/forgot-password.js
test/handlers/user/resend-email-confirmation.js
test/handlers/user/signup.js
test/mocks/server-methods.js

Fixes #1710.
This is a precursor to npm/mustache-mailer#5 to guarantee that upstream dependency changes won't result in regression of email data and content sent by the app.
Note that these assertions are correct for existing functionality, even if some results are not as intended. These will be fixed after `mustache-mailer` is updated.

Add assertions for expanded email data to facet or handler tests that send email

---

assets/styles/typography.styl

I'm not sure if this has been raised separately, but it's been bugging me for some time and I wanted to send a PR to fix it.
When there's an overflowing `pre` tag with `code` inside, the grey background drifts with the scroll, as per:
This change fixes the `code` element with a change to `display: inline-block` and `min-width: 100%` to ensure it stretches across both the width of the entire page (to emulate the `block` style) and the width of the overflowing `pre`, as per:
Note that I took care to keep the scrollbar in it's position (with the white background), otherwise I think the CSS could be simplified (maybe).
Anyway... keep on doing the great stuff :heart:

Fix drifting code bg when in overflowing pre

---

assets/styles/forms.styl

You can see how it is with dark system theme without background color:

added missed background color for form inputs

---

templates/user/tokens.hbs

Auth tokens generated via a cli log-in are not technically one-time
tokens.  They are multi-use tokens.
Very minor copy edit.  Not urgent.

Don't call auth tokens one-time tokens

---

assets/styles/index.styl

Hi
variables.styl needs the color `npmred`
https://github.com/npm/newww/blob/master/assets/styles/variables.styl#L54
reset.styl also need colors to define the `hr` element 
https://github.com/npm/newww/blob/master/assets/styles/reset.styl#L27
and the `body` element
https://github.com/npm/newww/blob/master/assets/styles/reset.styl#L74-L75
Therefore, colors.styl should be imported first.

fix(CSS): change imports order since colors are needed by variables

---

templates/package/access.hbs
templates/package/show.hbs

@aredridel I believe that this should fix https://github.com/npm/newww/issues/1730
I couldn't figure out how to run the site locally (I think it's still not possible) so I wasn't able to check for any unintended side effects. I don't think there would be as the only relevant difference between `{{{` and `{{` is that the latter escapes html and the former doesn't.

Use handlebars {{ instead of {{{ to escape html on package description

---

templates/org/payment-info.hbs

This restarts payment on an organization for a customer that has not
deleted their account or the license for this (deleted by stopping
payment entirely)
Addresses #1708

Add restart button to payment info page

---

templates/package/tutorial.hbs

I found a link in the tutorial on `https://www.npmjs.com/package/{package}/tutorial` which wasn’t clickable. I also changed the text inside the link from being a URL to a more helpful human readable text. If you’d rather like a different text I’m ok with changing it :)
P.S. I found some weird mixture of spaces and tabs used for indentation which I didn’t change, but it might be worthwhile to look into.

Fix broken links in tutorial

---

facets/enterprise/buy-license.js
facets/enterprise/show-verification.js
package.json
test/enterprise/buy-license.js

Explicitly bump `npm-email-templates` to version `1.10.1` in order to pick up the latest [npmo welcome email](https://github.com/npm/email-templates/pull/21) (which is still not in staging or production for some reason).
Also update the URL we use for npmo installation requirements, which has its own page with updated content.

Bump npm-email-templates dependency and update npmo requirements URL

---

package.json
test/company/contact-support.js
test/enterprise/buy-license.js
test/enterprise/find-license.js
test/enterprise/trial-signup.js
test/enterprise/verification.js
test/handlers/user/email-edit.js
test/handlers/user/forgot-password.js
test/handlers/user/resend-email-confirmation.js
test/handlers/user/signup.js

This is the final step in a long, drawn-out process to finally squash the `from: website@npmjs.com` problem with emails sent from newww (as described in npm/email-templates#18)! \o/
Previous steps leading to this point:
Phew! I'll be glad when this is done :wink:

Bump mustache-mailer dependency and update email test assertions

---

handlers/homepage.js
package.json

This switches us to the new async version of `npm-explicit-installs`, this has some benefits:
* it now shows the actual publication dates/versions.
* it makes it easier to swap in a component fed by another data-source.

switch to new async npm-explicit-installs

---

adapters/plugins.js

totally forgot to remove the email service from the plugins file (which is not tested via unit tests - another good thing about this transition away from non-hapi-based plugins).
whoops :-(

removes email service from plugins

---

package.json
templates/homepage.hbs
templates/layouts/default.hbs
templates/partials/package-widget.hbs

I've upgraded to the newest version of `npm-explicit-installs`, this version:
* supports proxies (which is important for big companies).
* has a bin for editing the packages on the home-page (this is only important for `npmo`).
* I also fixed a display bug I noticed: npmo has no user pages, but we still linked to user-pages.

upgrade to new version of npm-explicit-installs

---

package.json

__Note:__ We can't merge this to master until #1465 is merged. (`boom` requires __Node.js v4.0+__.)
Edit: I should probably rebase to the Node.js 4 update branch.

Updated the "boom" dependency.

---

adapters/plugins.js
adapters/qs.js
integration/user-to-org.js
package.json

Breaking changes are:
- move to ES6 in `vision` and `boom`
- stop using `qs` to parse URL parameters in hapi (we don't use any extended form parameters)
- change how `crumb` interacts with CORS, but we don't enable CORS at all

update to hapi 12.1.0 and attendant modules

---

presenters/package.js

This will make new versions appear instantly rather than waiting for cache timeout.

Use per-version cache keys for package readmes and descriptions

---

assets/images/osi.svg
assets/styles/typography.styl
package.json
presenters/package.js
templates/package/show.hbs

This relatively small PR attempts to add a small green OSI circle logo (and accompanying trademark symbol) beside the license information of packages that are licensed on OSI-approved ("open source") terms.
I am not sure that I went about the presentation side of things correctly, and will add a few line comments here and there. I'm flying blind without a full test env, but think I've at least got kinda-sorta close to something presentable.
Thanks to all!

Show OSI logo on open source package pages

---

templates/homepage.hbs

At least in Australia, "get a job" is quite insulting... it is only ever used to imply someone is a homeless bum that is draining the economy... especially as the presupposition of it is that you don't have a job, so such connotations are reasonably expected... "get hired" is a good alternative that doesn't imply such a thing, as the presupposition is just you want to be hired, rather than you are missing anything.

get a job => get hired
