npm/newww

package.json
=> remove duplicate deps

test/fixtures/mock-server-methods.js
Goes with https://github.com/npm/newww/commit/4379127deba76b0c395c7e7f61b34170c6d728e1
=> Test for fixed dlcounts

CONTRIBUTING.md
just a simple fix for new contributers
=> updated CONTRIBUTING.md for #518

templates/layouts/default.hbs
=> add npm weekly to menu

package.json
fixes:
https://staging.npmjs.com/package/catjs
https://staging.npmjs.com/package/cordova
https://staging.npmjs.com/package/kea-config
=> Frontmatter fix

templates/company/index.hbs
Using Schema.org can provide [better looking listings](https://developers.google.com/webmasters/structured-data/customize/social-profiles) in the search engines, especially Google.
Structured data can be tested with https://developers.google.com/webmasters/structured-data/testing-tool/
=> add Schema.org structured data for organization

assets/scripts/index.js
as per discussion [thus far](https://github.com/npm/newww/issues/513#issuecomment-70174406)
=> focus search input when / key is pressed (#513)

config.js
=> there another host that mailchimp needs

facets/registry/presenters/package.js
=> delete homepage if it’s not a URL

facets/user/billing.js, lib/csp.js, lib/environment.js, server.js, test/adapters/redis-sessions.js, test/fixtures/setupServer.js, test/fixtures/users.js, test/mocks/models/customer.js, test/services/downloads.js, test/services/registry.js, test/services/user.js, test/user/billing.js
Here's what you see when you're missing stuff:
=> R2 environment

routes.js
=> add a google verification route

package.json
=> bump hiredis to 0.2 for iojs compatiblity

templates/layouts/default.hbs
=> add jobs link to top nav

assets/scripts/index.js, assets/styles/highlights/syntax-variables.styl, assets/styles/markdown.styl, assets/styles/typography.styl, templates/enterprise/complete.hbs, templates/errors/internal.hbs, templates/errors/not-found.hbs, templates/layouts/default.hbs, templates/user/password-changed.hbs, templates/user/profile-not-found.hbs
Fixes this, among other things:
=> hljs cleanup

assets/scripts/index.js
per @silverwind's https://github.com/npm/newww/issues/513#issuecomment-72329897
=> (also) Bind search shortcut to '-' (easier on non en-us keyboards)

templates/user/login.hbs
a cheap trick to prevent this:
note: we should still fix that object Object thing too!
=> make username and password required to avoid empty form submissions

assets/styles/_header.styl
This is a bit more opinionated, and not being fully versed in your visual design do so as you see fit. Also, I'm not 100% up to date on stylus convention, I think I've done this correctly.
Thoughts?
=> Adding hover styles for global search

assets/scripts/add-active-class-to-links.js, assets/scripts/autoselect-inputs.js, assets/scripts/billing-cancel.js, assets/scripts/billing.js, assets/scripts/date-formatting.js, assets/scripts/email-obfuscate.js, assets/scripts/hiring.js, assets/scripts/index.js, assets/scripts/keyboard-shortcuts.js, assets/scripts/npm-expansions.js, assets/scripts/payments.js, assets/scripts/star.js, assets/scripts/user-content.js, assets/scripts/what-npm-is-for.js, routes/public.js
- use a separate file for each discrete script
- do not attach to window if not needed
- do not require query when not needed
=> refactor browser scripts

.travis.yml
Should make builds a lot faster, because http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
=> sudoless travis

assets/scripts/date-formatting.js
Update timestamps on the page every few seconds
=> Continuous date formatting

handlers/package.js, templates/partials/package-header.hbs, test/handlers/package.js
This will allow us to ship r2-powered www without all the private package bells and whistles.
=> hide the package nav behind FEATURE_ACCESS env var

facets/user/show-email-edit.js, facets/user/show-password.js, models/user.js, package.json, test/fixtures/email_edit.js, test/fixtures/users.js, test/handlers/user/email-edit.js, test/handlers/user/password.js, test/models/user.js
=> Fix /password and /email-edit

assets/scripts/what-npm-is-for.js
It would be nice to have that in the list, right? :)
//cc @zeke @isaacs
=> Added react to the list.

facets/user/show-logout.js, models/download.js, services/user/methods/sessions.js
=> updates logout handler

facets/user/show-resend-email-confirmation.js, routes/authenticated.js, templates/user/profile-edit.hbs, test/handlers/user/resend-email-confirmation.js, test/mocks/server-methods.js
Please note that the link in the template is totally just a placeholder for proof of concept :-)
=> adds resend confirmation email route

facets/user/show-forgot.js, models/package.js, templates/user/password-recovery-form.hbs, test/handlers/star.js
all fixed!! this is ready for review.
cc: @zeke @ceejbot
=> Update star routes

templates/registry/package-page.hbs
=> Fix broken links in depedents and dependencies

facets/company/show-send-contact.js, templates/company/contact.hbs, test/company/contact-support.js
=> allow users to report security issues

templates/layouts/default.hbs
Hi, can we try apply [Search Box](https://developers.google.com/structured-data/slsb-overview)?
This change is supposed to generate the following template:
debugger: https://developers.google.com/structured-data/testing-tool/
```html
<body itemscope itemtype="http://schema.org/WebSite">
<meta itemprop="url" content="https://www.npmjs.com/">
<form id="npm-search" action="/search" method="get" itemprop="potentialAction" itemscope itemtype="http://schema.org/SearchAction">
<meta itemprop="target" content="https://www.npmjs.com/search?q={q}">
<input name="q" value="" type="search" id="site-search" placeholder="find packages" tabindex="1" autocorrect="off" autocapitalize="off" itemprop="query-input" />
<input type="submit" id="site-search-submit" />
</form>
</body>
``
=> Update default.hbs with Search Box schema

facets/registry/show-search.js
This was leading me to some very goofy search results.
=> Fix url building for current url of paginated results.

facets/company/show-whoshiring-payments.js
=> fix hiring ad payment bug

handlers/ops.js, lib/git-head.js, lib/stamp.js, server.js, test/handlers/ops.js, test/mocks/server.js
This one's for you, @ceejbot 
- add tests for `/_monitor/ping`
- add tests for `/_monitor/status`
- extract `git-head` into a standalone module for re-use
- add `gitHead` property to `/_monitor/status` response object
=> Monitoring Improvements

package.json
backstory: https://github.com/npm/npm-expansions/issues/335
=> moar expansions

assets/scripts/what-npm-is-for.js
[DocPad](https://docpad.org/)'s plugin system is powered by npm: https://www.npmjs.com/search?q=docpad-plugin and was one of the first (if not the first) plugin system for node
=> Added docpad to what npm is for

templates/registry/package-page.hbs
Show a count of the number of projects dependent on a package.
=> Show number of dependents. Fixes: #812

facets/user/show-forgot.js, test/handlers/user/forgot-password.js
=> fixes /forgot bug for unique email

facets/user/show-email-edit.js, templates/company/contact.hbs
=> Tiny little r2 bugs

facets/user/show-forgot.js, templates/user/password-recovery-form.hbs, test/handlers/user/forgot-password.js
This is a fix for https://github.com/npm/newww/issues/815
=> humane errors on /forgot page

assets/styles/layout.styl
https://github.com/npm/newww/pull/619
https://github.com/npm/newww/issues/550
=> simplify and fix styles for last publisher. all credit goes to @elmasse

handlers/homepage.js, handlers/package.js, models/package.js, test/models/package.js
@ceejbot @zeke what do you think about this approach? if it's kosher, I'll go ahead and update other spots where we're using `Package.list()`.
=> enables list-specific TTLs

presenters/package.js
Fixes https://github.com/npm/newww/issues/827
=> show collaborators sidebar even if there’s only one collaborator

adapters/bonbon.js, assets/scripts/package-access.js, assets/styles/forms.styl, assets/styles/layout.styl, templates/layouts/default.hbs, templates/partials/collaborator.hbs, test/handlers/access.js, test/handlers/homepage.js
=> make it slightly difficult to revoke your own access to package

templates/partials/email-verify-nag.hbs, templates/user/billing.hbs, templates/user/email-confirmed.hbs, test/fixtures/users.js, test/handlers/customer.js
Fixes https://github.com/npm/newww/issues/843
=> don’t display payment form to unverified users

templates/user/billing.hbs
=> adds user-friendly messaging for re-logging-in via the cli

templates/enterprise/index.hbs
=> adds button to enterprise license purchase page (fixes #760)

adapters/bonbon.js, lib/feature-flags.js, models/user.js
Code inspection of the massive changes in the R2 branch did turn up some areas for cleanup: 
- don't make any more than one mailchimp client, since the config is invariant
- don't recalculate feature settings, since they're also invariant
=> Probably not fixing the memory leak.

assets/styles/layout.styl
Fixes https://github.com/npm/newww/issues/895
=> Remove CSS rule hiding THEAD elements

.jshintrc, README.md, assets/scripts/twitter-tracking.js, lib/csp.js, templates/partials/twitter-tracking.hbs, templates/user/billing.hbs, templates/user/profile.hbs, test/csp.js, test/handlers/customer.js, test/handlers/user/profile.js
A followup to https://github.com/npm/newww/pull/911
=> twitter tracking

assets/scripts/banner.js
=> don’t show banner on the billing page

handlers/package.js, test/handlers/package.js
I removed all instances of `promise.cancel()` because I'm not sure how to cancel the promise with `.props` (as per https://github.com/petkaantonov/bluebird/wiki/Error:-circular-promise-resolution-chain)
=> parallelizes the requests on the package page, fixes #826

templates/user/billing.hbs
Laurie switched the tag definitions around a bit, so updating to reflect.
=> add Twitter tracking code for visiting sign up page

README.md
cc @linclark, who is going through the process today.
=> update dev instructions in readme

assets/scripts/index.js, assets/scripts/twitter-tracking.js, templates/layouts/default.hbs, templates/partials/twitter-tracking.hbs, templates/user/billing.hbs
so we have a local reference for the twitter pixel ids
=> annotate twitter codes

.travis.yml, assets/scripts/fetch-packages.js, assets/scripts/index.js, assets/templates/profile-package.hbs, facets/user/show-packages.js, models/user.js, package.json, routes/public.js, templates/user/profile.hbs, test/adapters/bonbon.js, test/handlers/user/edit-profile.js, test/handlers/user/profile.js, test/models/user.js
This still needs tests (will get to it on Monday), but here's the low-down:
1) I'm now chopping up the package list to 100, and adding more via ajax on user request
2) I've created a template to make adding the packages to the page easier, but had to remove the `truncate` helper function because I'm not sure how to add that back in (can look into it next week, though if @zeke knows, that'd be mega helpful)
3) I'm using a huge button to handle the user-request bits... not sure if a different styling would be better?
feedback very much welcome!!
=> first run at fixing painfully slow user profile pages (fixes #854)

facets/enterprise/show-contact-me.js, facets/enterprise/show-trial-signup.js, facets/enterprise/show-ula.js, handlers/customer.js, lib/utils.js, services/npme/methods/sendData.js
I would like to push this up to staging before we merge it in :-)
=> address broken IP address (fixes #858)

handlers/customer.js, templates/user/billing.hbs
This adds a coupon code field to the form and passes the coupon code to license api.
=> add coupon code handling

lib/cache.js, presenters/package.js, test/cache.js, test/presenters/package.js
- Adds getKey and setKey to lib/cache.js
- Enables caching of package readmes and descriptions to speed up package page load
=> Cache rendered readmes

adapters/bonbon.js, facets/user/show-profile.js, lib/cache.js, models/user.js, test/adapters/bonbon.js, test/cache.js, test/fixtures/users.js, test/handlers/access.js, test/handlers/collaborator.js, test/handlers/customer.js, test/handlers/fallback.js, test/handlers/homepage.js, test/handlers/package.js, test/handlers/star.js, test/handlers/user/confirm-email.js, test/handlers/user/edit-profile.js, test/handlers/user/email-edit.js, test/handlers/user/forgot-password.js, test/handlers/user/login.js, test/handlers/user/password.js, test/handlers/user/profile.js, test/handlers/user/resend-email-confirmation.js, test/handlers/user/signup.js, test/models/collaborator.js, test/models/customer.js, test/models/user.js
It took a while due to yaks needing shaving, but finally we have cached isPaid information!
(The biggest issue was getting all the tests to pass - they should be doing so now.)
The included commits give a pretty good idea of what went down in the process of putting together this PR.
=> cache is-paid status

templates/user/profile.hbs, test/fixtures/customers/bob.json, test/fixtures/customers/index.js, test/handlers/user/profile.js, test/models/user.js
with a test and everything :-)
=> changes profile page messaging for paid users (fixes #965)

assets/scripts/what-npm-is-for.js
Celebrating the work by @brianleroux and team to get cordova's plugins into npm :-)
=> Adding cordova to what npm is for

assets/scripts/remove-private-module-signup.js
Quick script addition to remove part of static page.
Fixes #1043
=> Issue 1043

assets/templates/profile-package.hbs, templates/user/profile.hbs, test/handlers/user/profile.js
Adding the version to the template.
Fixes #1040
=> Versions added to the template

assets/scripts/index.js, assets/scripts/remove-private-module-signup.js
This ended up being pretty visually janky, no matter how we worked with it.
Eventually we'll revisit, with the idea that we can handle this server-side.
Reopening #1043
=> Revert 1043 fix

routes/public.js, test/handlers/redirects.js
Fix #1055
Make sure scoped packages are included in a redirect
=> Make sure scope is included in a redirect

assets/styles/index.styl, assets/styles/tips.styl, facets/user/show-login.js, locales/en_US/user.js, package.json, templates/user/login.hbs
Fix #1047
- Add tips
- Add marky-markdown support
- Compliment removed
=> Add npm-tips to login page.

adapters/bonbon.js, handlers/access.js, handlers/customer.js, models/customer.js, models/user.js, test/adapters/bonbon.js, test/fixtures/customers/bob_subscriptions.json, test/fixtures/customers/happy.json, test/fixtures/customers/index.js, test/handlers/access.js, test/handlers/collaborator.js, test/handlers/customer.js, test/handlers/homepage.js, test/handlers/package.js, test/handlers/star.js, test/handlers/user/confirm-email.js, test/handlers/user/edit-profile.js, test/handlers/user/email-edit.js, test/handlers/user/forgot-password.js, test/handlers/user/login.js, test/handlers/user/password.js, test/handlers/user/profile.js, test/handlers/user/resend-email-confirmation.js, test/handlers/user/signup.js, test/models/customer.js, test/models/user.js
The license API has changed a bit; this PR allows us to launch the license API to production without affecting users while we work on the next bits.
cc @bcoe
=> feature parity with the updated license api

routes/public.js
=> Add caching for all static content but index.js

package.json
The package.json has been updated to reflect the most current version of npm-humans.
=> Update npm-humans dependency to v2.8.0

package.json
updated npm-humans to version 2.8.1.
=> updated version number for npm-humans

.travis.yml, assets/styles/forms.styl, templates/user/profile-edit.hbs
=> fixes weird styling bug on profile edit page

handlers/access.js, handlers/customer.js, templates/package/show.hbs, test/handlers/access.js, test/handlers/customer.js, test/handlers/package.js
making way for new ones to come :-)
=> removes feature flags that are no longer needed

.gitignore, lib/environment.js, lib/external-request.js, models/package.js, package.json, test/fixtures/users.js, test/handlers/homepage.js
@jefflembeck @ceejbot please scrutinize this PR. I don't think it we will have any production problems if we merge this code in, but I'd rather be safe than sorry.
=> NOW WE CAN REMOTE LIKE REAL PEOPLE OMG

assets/scripts/banner.js, assets/styles/_header.styl, assets/styles/layout.styl, assets/styles/typography.styl, templates/layouts/default.hbs
Banner that doesn't blow out a screen
=> Better banner

routes/public.js
… until the actual product page is launched.
=> adds a 301 to point /orgs to a signup landing page

routes/public.js
Reverts npm/newww#1125
Turns out we don't quite need this form after all :-)
=> Revert "adds a 301 to point /orgs to a signup landing page"

assets/scripts/buy-enterprise-license.js, assets/scripts/payments.js
=> CSS selector for getting stripe key was insufficiently specific

package.json
=> Update npm-humans to 2.9.0

services/user/methods/sessions.js, test/handlers/user/logout.js, test/handlers/user/signup.js, test/mocks/server-methods.js, test/services/user.js
In response to https://github.com/npm/newww/issues/1113
This feels incomplete, but airplane head isn't sure what else is needed... thoughts, @jefflembeck, @ceejbot?
=> Upgrade session tests

package.json
now with @cowperthwait and @ncawthon!
=> updates npm-humans to latest

handlers/org.js
i think this is all we need left to seekritly put this branch into prod :-)
=> puts all org methods behind the FEATURE_ORG_BILLING flag

templates/user/billing.hbs
Payment form was missing.
That was bad.
=> Missing customer check

templates/org/create.hbs, templates/org/index.hbs
Copy changes — many seemingly trivial — by @cowperthwait and @kaseybyrne
=> 2015 08 13 marketing copy updates

.gitignore, models/user.js, package.json
- needless use of __dirname
- add the dev env to the dev script
- add .swp files to .gitignore (hi, vim! Bye, vim!)
- instantiate Error with new, though it doesn't matter in V8, it does in JS in general.
=> Small fixes

handlers/org.js, models/customer.js, templates/org/info.hbs, test/fixtures/orgs.js, test/handlers/org.js
This legitimately needs some refactoring, but its functionality and tests work for right now.
=> Unpaid paid

handlers/customer.js, templates/user/billing.hbs, test/handlers/customer.js
what tests am I missing?
I have refactored some of the customer handler tests to clarify what's happening, and when. other than that, though, the only way to guarantee that certain functions are being called when we want them to be called is to use sinon spies. thoughts? ideas? halp?
=> Missing payment form

assets/scripts/tabs.js, templates/org/info.hbs
Make sure it stays at the top of the page when you click the tab nav.
Make sure the back button is supported.
Fix #1154
=> Support deep linking for tabs

assets/styles/org.styl, templates/org/index.hbs
I have [bent CSS to my will](https://twitter.com/rockbot/status/635963757638750208).
=> Price area styling

templates/org/create.hbs
Added helper text and placeholders and a link to explanatory docs.
=> Clarify difference between name and scope

agents/org.js, assets/styles/forms.styl, handlers/customer.js, models/customer.js, package.json, routes/authenticated.js, templates/org/create.hbs, templates/org/index.hbs, templates/partials/email-verify-nag.hbs, templates/user/email-confirmed.hbs, test/agents/org.js, test/handlers/customer.js
This PR is for handling the `/org/create` route - whether you're paid or not.
There is almost certainly stuff that's missing in here; I wanted to get this PR made, though, so that we can start working through all the pieces as a team.
=> Org Creation

assets/styles/components/_nav.styl, assets/styles/org.styl, assets/styles/variables.styl, handlers/customer.js, handlers/org.js, models/customer.js, routes/authenticated.js, templates/partials/billing-info.hbs, templates/ui-docs/index.hbs, templates/user/billing.hbs, test/handlers/org.js, test/models/customer.js
The billing page has been updated from every angle possible - it only shows active orgs. It allows you to unsubscribe (without deleting), it shows your last date that the organization is going to be active, it blocks you from accessing orgs that you're not subscribed to.
It has also been updated from the aspect of appearance to better match the design.
=> Billing page

assets/styles/typography.styl, templates/user/profile.hbs, test/handlers/user/profile.js
Slight design change implemented and create org link added.
=> New profile sidebar

assets/scripts/tabs.js, handlers/org.js, package.json, test/handlers/org.js, test/mocks/server.js
This makes it so we don't have a major crash if a user doesn't exist while adding to an org.
=> Add user exception handling

handlers/customer.js, test/handlers/customer.js
this will address @chrisdickinson's issue that he was seeing earlier :-)
=> Org redirect for pm

package.json
this version contains the memory management fixes
=> bumping marky-markdown

assets/styles/_header.styl, templates/layouts/default.hbs
See: #1074.
--
Cc: @aredridel.
=> Make clear button be accessible on small screens

handlers/customer.js, handlers/org.js, models/customer.js, templates/user/email-confirmed.hbs, test/handlers/customer.js
When creating an organization, the creator wasn't being added as a sponsored user.
Fixes #1272
=> Creating an Organization doesn't sponsor creator

facets/user/show-login.js, templates/user/login.hbs
=> Handle redirects after login properly, and explicitly set one for /orgs?join-beta

models/customer.js
This provides us with a handler for the 500 for the time being.
=> 409 return status isn't ready yet in production like it is in staging

agents/org.js, handlers/customer.js, models/customer.js, test/handlers/collaborator.js, test/handlers/customer.js
Wider error handling for org agent and customer model.
=> Error handling

templates/org/info.hbs
Changing Edit User to Save Changes because that wording was confusing
Fixes #1261
=> This wording was confusing

assets/styles/markdown.styl
See: #1119.
This fixes: #1114.
=> Fix truncating long headings related issue

templates/org/info.hbs
This is a temporary fix as we add another status to the API
=> Removing ability to edit payment status

agents/org.js, handlers/customer.js, test/handlers/customer.js
=> sends 409s back to org/create with user-friendly messaging

facets/enterprise/buy-license.js, facets/enterprise/find-license.js, facets/enterprise/license-options.js, facets/enterprise/show-index.js, facets/enterprise/show-ula.js, package.json, templates/enterprise/check-email.hbs, templates/enterprise/clickThroughAgreement.hbs, templates/enterprise/complete.hbs, templates/enterprise/contact-me.hbs, templates/enterprise/find-license.hbs, templates/enterprise/index.hbs, templates/enterprise/invalid-license.hbs, templates/enterprise/license-error.hbs, templates/enterprise/license-options.hbs, templates/enterprise/license-paid.hbs, templates/enterprise/thanks.hbs, templates/layouts/default.hbs, test/enterprise/buy-license.js, test/enterprise/find-license.js, test/enterprise/index.js, test/enterprise/license-options.js
We need to land these changes to the email copy at the same time:
https://github.com/npm/email-templates/pull/14
I've already published the updated installer:
https://www.npmjs.com/package/npmo
=> renaming npmE to npm on-site

facets/user/show-login.js, routes/public.js
Also fixes redirects via /login for already logged in users
Fixes #1257
=> Fix the redirect to the orgs beta for already logged in users

templates/company/contact.hbs
Updated office address and google maps short url.
Addresses #1222
=> Updated office address

handlers/package.js, templates/package/show.hbs
=> Hide downloads on scoped packages

package.json
let's not forget those little npmo email tweaks that @cowperthwait made ;-)
=> updates to latest email templates

routes/public.js, test/handlers/redirects.js
Work around http response splitting bug that occurs in node > v0.10
=> Http response splitting

assets/scripts/index.js, assets/scripts/js-check.js, assets/scripts/switch-submission.js, assets/styles/forms.styl, assets/styles/typography.styl, templates/org/info.hbs
=> Paid unpaid redux

routes/public.js, test/handlers/redirects.js
URLs that have redirects with user input must be validated.
=> Validation of url

models/customer.js, test/models/customer.js
=> Trigger 500

facets/registry/show-search.js
@aredridel Please have a look :bow:
=> Fix next page bug of search

assets/styles/_header.styl
Bonus: Fixes some alignment issues on mobile size!
=> Tighten up whitespace a bit in the top bar, and tighten up the implementation a lot

assets/scripts/validator.js, assets/styles/org.styl, handlers/customer.js, handlers/org.js, routes/authenticated.js, templates/org/billing.hbs, templates/org/create.hbs, templates/org/transfer.hbs, test/handlers/customer.js, test/handlers/org.js
Fixes a couple of things that were bothering me, UI-wise
This includes email verification on pages and the re-use of a btn class.
This also includes validation of usernames and org scopes at every step along the way, which addresses #1396
=> Org flow cleanup

handlers/org.js, templates/org/info.hbs, test/fixtures/orgs.js, test/handlers/org.js
The form fields were visible for other org users.
They are unable of actually doing anything with those fields, but the UI
is confusing and misleading
=> Only show controls to those permitted

templates/user/billing.hbs, templates/user/profile.hbs, test/handlers/user/profile.js
This should address #1399 
I'd like a look-over on this from @seldo / anybody who should be in charge of language
=> Language fixing + link fixing for private modules

assets/scripts/tabs.js, assets/styles/components/_nav.styl, templates/org/info.hbs, templates/ui-docs/index.hbs
We've added nav-4, nav-4 is a tab-style nav that we will be using for
the org screen. It has been created, added to the ui-docs and to the org
page.
This commit also cleans up a bunch of the nav-related css
=> New look for tab-based navigation

package.json, server.js
Trying out newrelic to see what it can give us on the browser end.
=> Set up newrelic

.gitignore
=> adds newrelic agent log to .gitignore

templates/user/billing.hbs
Style regression came about from refactor of nav/nav-container styles.
=> Fix style regression

templates/homepage.hbs
=> Fixed the Node.js link for "installing npm".

templates/org/info.hbs
Incorrect handlebars nesting was making it so deleting a user wasn't working.
=> Fix nesting for org

handlers/org.js
This will throw a 500 otherwise.
=> request.logger, not response

handlers/org.js, templates/org/transfer.hbs, test/handlers/org.js
=> fixes bug where users got 500s if they tried to transfer to an already-occupied scope

handlers/org.js, routes/public.js, test/handlers/org.js
=> redirects orgs pages to /org/{org} from /orgs/{org}

facets/user/show-profile.js, handlers/org.js, templates/org/info.hbs, templates/user/profile.hbs, test/adapters/bonbon.js, test/fixtures/orgs.js, test/fixtures/users.js, test/handlers/org.js, test/handlers/user/edit-profile.js, test/handlers/user/profile.js
we need a way to only present information to people who are allowed to see it.
thoughts? opinions?
=> Org permission breakdown

templates/enterprise/contact-me.hbs
As requested by the sales team :-)
=> updates wording on on-site contact page

agents/team.js, handlers/team.js, routes/authenticated.js, templates/team/show.hbs, test/agents/team.js, test/fixtures/teams.js, test/handlers/team.js
those team page packages. so hot right now.
=> Team page packages

assets/styles/_header.styl
=> Fix the line-height of the navigation items

package.json
... to `^2.13.0`
As [suggested](https://github.com/npm/humans/pull/31#issuecomment-155480617) by @aredridel. :smile:
=> Explicit update of npm-humans

agents/team.js, assets/scripts/add-packages-to-teams.js, assets/scripts/add-users-to-teams.js, assets/scripts/index.js, assets/styles/org.styl, assets/templates/team-package.hbs, handlers/team.js, models/user.js, routes/authenticated.js, templates/org/teams.hbs, templates/team/add-package.hbs, templates/team/show.hbs, test/agents/team.js, test/fixtures/teams.js, test/fixtures/users.js, test/handlers/team.js, test/models/user.js
team and super admins can now add packages to their teams.
note: they can add either packages from other teams or any package that they have write access to (currently called "personal" packages). any/all help with naming would be greatly appreciated!
=> Team add packages

handlers/team.js, templates/team/show.hbs, test/handlers/team.js
when you uncheck the box, the checkbox doesn't send anything through, and our Joi validation was catching it.
Also there was a parameter mismatch.
all better now!
=> fixes a joi validation error (fixes #1519)

templates/org/teams.hbs, templates/team/show.hbs
not everyone gets to click on the fancy buttons. now you only see them if you have permission to :-)
=> Permission-ed buttons

agents/org.js, handlers/org.js, test/agents/org.js, test/handlers/org.js
also clarifies the error message and fixes tests so that we don't accidentally err in the same way in the future.
=> fixes org redirect on user add error (fixes #1514)

assets/scripts/add-users-to-teams.js, templates/team/add-package.hbs
see commits for details of PR.
but basically: now when you press `Enter` on the add-user page, it adds the user to the list, without submitting the whole form.
=> Add user hijack enter

agents/team.js, test/agents/team.js, test/handlers/team.js
This prevents a couch dogpile from the user-acl side.
=> use mulitpackage format when adding pkgs to teams

assets/scripts/add-users-to-teams.js
fixes #1513
.. this isn't my favorite way to fix this... we'll improve with client-side handlebars templates
=> adds link to add user to org when adding non-member to team 

templates/org/teams.hbs
=> fixes perms issue (fixes #1546)

assets/scripts/switch-submission.js, assets/styles/forms.styl, templates/team/show.hbs
so now it looks like this: 
(will probably still need a bit of styling, cc @ncawthon :-)
=> removes Save button for switches when editing package perms

templates/org/members.hbs, templates/org/show.hbs, templates/org/teams.hbs, templates/partials/org-nav.hbs
=> DRYs up the org nav and makes payment tab go to billing page (fixes #1523)

agents/customer.js, handlers/customer.js, templates/partials/billing-info.hbs, templates/user/billing.hbs, test/handlers/customer.js
=> Warn clearly on stop all payments what this will do to orgs

templates/user/billing.hbs
=> Add button to delete private modules

agents/team.js, handlers/team.js, templates/org/teams.hbs, test/agents/team.js, test/handlers/team.js
Not mergeable just yet. Adding tests and error handling.
=> Teams can now be deleted! Fixes #1574.

templates/user/billing.hbs
May need more refined criteria -- @chrisdickinson? @ncawthon?
=> Show the link to sign up for private modules if they have no private modules subscriptions

handlers/org.js, routes/authenticated.js, templates/user/billing-confirm-cancel.hbs, templates/user/billing.hbs, test/handlers/org.js
=> Confirm deleting subscriptions

templates/enterprise/contact-me.hbs
Many apologies for the delay, @cowperthwait and @kaseybyrne!
=> adds AdWords 1x1 on on-site contact me page (fixes #1454)

handlers/customer.js, test/handlers/customer.js
to replicate the bug:
* log in as a user with no payment information
* click on "sign up for private modules" on the profile page
* get 500 
what's expected:
* the user should be taken to the subscriptions page
===
the following PR fixes the bug, but I can't replicate the bug in tests. Any thoughts on how to test this properly?
=> fixes bug where unpaid users get 500 instead of billing page

agents/customer.js, handlers/org.js, test/handlers/org.js
Dependent on #1657 
This is the way we restart an organization.
Promisify getAllSponsorships for later use
Switch to switch for updateType
Promisify cancelSubscription
Add the handler to restart an org
=> Restart org function

templates/user/billing-confirm-cancel.hbs
spacing needs to happen as well
=> This should at least be centered and narrow

templates/partials/form_csrf.hbs, templates/partials/form_honeypot.hbs, templates/partials/form_security.hbs, templates/user/login.hbs
=> Removed the honeypot from the sign in page.

assets/styles/_header.styl, templates/layouts/default.hbs
=> Fix constrained width on nav

assets/styles/forms.styl
=> Embolden the border on the paid/unpaid switches

assets/styles/forms.styl, assets/styles/tables.styl, templates/org/members.hbs, templates/org/teams.hbs, templates/user/billing.hbs
addressed some table alignment issues on the packages tab
=> Package table align

gulpfile.js, lib/startup.js
=> Stop caching templates in dev, avoiding need for server restart while editing

package.json
=> bump marky-markdown to 6.0.0

assets/styles/layout.styl, assets/styles/typography.styl, gulpfile.js, handlers/package.js, package.json, templates/package/show.hbs, test/handlers/package.js
Sort of like the CMS-driven upsell box, but way smaller, and fewer features.
Deployamating to stage coach presently.
=> Marketing sidebar blob

facets/user/show-forgot.js, facets/user/show-password.js, models/user.js, test/handlers/user/password.js
This may help diagnose some of the user and password reset errors we've seen
cc: @jonathanmarvens
=> Use verror and make logging consistent in reset password and password change flows

CONTRIBUTING.md
=> add security section to contributing

templates/package/tutorial.hbs
=> absolute link path to nodejs.org

templates/enterprise/index.hbs
thanks for the review @jonathanmarvens.
=> slight fix to grammar \o/

routes/public.js, templates/layouts/default.hbs, test/handlers/security-page.js
Do not land until https://github.com/npm/policies/pull/37 ships.
=> Move /security to /policies/security

adapters/bonbon.js, agents/package.js, agents/user.js, handlers/confirm-email.js, handlers/customer.js, handlers/email-edit.js, handlers/forgot.js, handlers/login.js, handlers/org.js, handlers/packages.js, handlers/password.js, handlers/profile.js, handlers/team.js, handlers/user.js, test/agents/user.js
we use the user agent a lot, hence lots of changes (but in the interest of not breaking anything between commits, this had to be one huge PR). apologies.
On the plus side: BYE BYE MODELS. WE HARDLY KNEW YE.
=> User model to agent

agents/download.js, handlers/homepage.js, handlers/package.js, test/agents/download.js
very similar to https://github.com/npm/newww/pull/1371, but a tad cleaner and totally up to date with master :-)
=> converts download model into an agent

integration/create-org.js, integration/onsite-trial.js
There are a few flaky tests, which seems to have been due to funky race conditions. These have been fixed, thanks to the beauty of promises!
Also, there may have been some ES6. Maybe. ;-)
cc: @aredridel
=> Fix integration tests

integration/create-org.js, integration/joinwhoshiring.js, integration/lib/fillStripeForm.js, integration/user-to-org.js
once again, dear readers, we have flaky integration tests, almost entirely due to race conditions. this is my attempt to remove as many of said race conditions as I can find, though i'm sure there are more... lurking in the shadows... harrumph.
=> some more code changes for integration tests

package.json, test/handlers/user/profile.js
There was a breaking change, but that's taken care of.
=> Updated "truncate" package dependency.

package.json
this should be good to go, no breaking changes afaik.
=> bump marky to 6.0.4

assets/images/osi.svg, assets/styles/typography.styl, package.json, presenters/package.js, templates/package/show.hbs
This supersedes and includes #1879
=> Show OSI logo on OSI-approved licensed packages

adapters/bonbon.js, agents/cms.js, agents/user.js, assets/scripts/vendor/google-analytics.js, assets/styles/layout.styl, assets/styles/typography.styl, gulpfile.js, handlers/cms.js, handlers/package.js, handlers/profile.js, lib/background-refresh-cache.js, lib/external-fetch.js, lib/redis-pool.js, lib/user-facts.js, package.json, templates/layouts/default.hbs, templates/package/show.hbs, test/adapters/bonbon.js, test/agents/cms.js, test/agents/user.js, test/fixtures/cms/index.js, test/fixtures/cms/promotion.json, test/handlers/package.js, test/user-facts.js, tools/cms-mock.js
=> Add marketing window on package pages

assets/styles/icons.styl, templates/org/payment-info.hbs
=> Just use an image rather than iconic SVG inlining for actions button
